charts project
Vahe101/react-graphs pull request #1
Opened 2021-02-10 14:03 UTC by Vahe101

2021-02-10 14:06 UTC, edotnet commented on src/components/Connected/Connected.jsx
> +    const [check, setCheck] = useState(true);
store chart type instead of boolean. such as 0 - brat, 1 - pie etc.

2021-02-10 14:06 UTC, edotnet commented on src/components/Connected/Connected.jsx
> +export default connect(
create mapStateToProps, mapDispatchToProps method

2021-02-10 14:07 UTC, Shitikyan requested changes

2021-02-10 14:07 UTC, Shitikyan commented on src/components/BarChart/index.jsx
> +            const randomColor = "#" + Math.floor(Math.random() * 16777215).toString(16);
what number is this?

2021-02-10 14:07 UTC, Shitikyan commented on src/components/Connected/Connected.jsx
> +    ({ users }) => ({ users }),
use variables instead of specifing everything here

2021-02-10 14:07 UTC, Shitikyan commented on src/components/PieChart/index.jsx
> +    const colors = [
Add Color Helper class

2021-02-10 14:07 UTC, Shitikyan commented on src/reportWebVitals.js
> +const reportWebVitals = onPerfEntry => {
remove this file

2021-02-10 14:07 UTC, Shitikyan commented on src/index.jsx
> +reportWebVitals();
remove this file

2021-02-11 14:35 UTC, hayko-karyan commented on src/components/BarChart/index.jsx
> +    const click = (event) => {
Rename this

2021-02-11 14:36 UTC, hayko-karyan commented on src/components/BarChart/index.jsx
> +    const [backgroundColor, setBacgroundColor] = useState(colors);
use correct name

2021-02-11 14:38 UTC, hayko-karyan commented on src/components/BarChart/index.jsx
> +        <div className="parent">
rename className

2021-02-11 14:39 UTC, hayko-karyan commented on src/components/Connected/Connected.jsx
> +import Button from "../../shared/Button/index";
not needed 'index'

2021-02-11 14:42 UTC, hayko-karyan commented on src/components/Connected/Connected.jsx
> +                <Button value="SimpleBarChart" onClick={() => { setCheck(1) }} />
not needed brackets

2021-02-11 14:43 UTC, hayko-karyan commented on src/components/Connected/Connected.jsx
> +    const [check, setCheck] = useState(0);
rename

2021-02-11 14:47 UTC, hayko-karyan commented on src/shared/colorsGenerate/index.js
> +        return arr;
not needed

2021-02-11 14:48 UTC, hayko-karyan commented on src/store/chartsData/reducers/allReducers.js
> +import { usersReducer } from "./";
?

2021-02-11 15:35 UTC, melqonyan99 commented on src/components/BarChart/index.jsx
> +    const onClickEvent = (event) => {
Please use friendly names for functions

2021-02-11 15:41 UTC, melqonyan99 commented on src/components/Connected/Connected.jsx
> +                    {contentVerification === 1 && (<div><SimpleBar data={users.items} /></div>)}
I think we don't need to use "div"

2021-02-11 15:43 UTC, melqonyan99 commented on src/components/PieChart/index.jsx
> +    const onClickEvent = (event) => {
Change function name with a most friendly name

2021-02-11 15:52 UTC, melqonyan99 commented on src/components/PieChart/index.jsx
>      const colors = generateRandomColor();
How you used this function without a parameter?
![image](https://user-images.githubusercontent.com/74979055/107661391-ae515680-6ca2-11eb-9fc8-1dc1753e2e95.png)

2021-02-11 16:26 UTC, melqonyan99 commented
Please also remove the vertical scrolling

2021-02-11 16:27 UTC, Shitikyan requested changes

2021-02-11 16:27 UTC, Shitikyan commented on src/components/BarChart/index.jsx
> +            const randomColor = (generateRandomColor(1))[0];
Please make this correct

2021-02-11 16:33 UTC, melqonyan99 commented
On click PieChart, I can't see color changing. Please check

2021-02-22 17:21 UTC, merged